import crypto from 'crypto';
import { env } from '../config/env';

export interface UploadSignatureResult {
  signature: string;
  timestamp: number;
  apiKey: string;
  cloudName: string;
  folder: string;
  publicId: string;
  public_id: string;
}

/**
 * Signs Cloudinary upload parameters using Cloudinary's documented SHA-1 process:
 * 1. Sort parameter keys alphabetically
 * 2. Join as key=value&key2=value2
 * 3. Append the Cloudinary API secret directly to the serialized string
 * 4. Compute SHA-1 hash and return hex digest
 *
 * NOTE: Cloudinary's signature algorithm uses direct SHA-1 hashing, NOT HMAC.
 */
export const signParameters = (
  params: Record<string, string | number>,
  apiSecret: string
): string => {
  if (!apiSecret) {
    throw new Error('Cloudinary API secret is required for signing');
  }

  // Filter out any undefined, null, or excluded parameters
  const keys = Object.keys(params)
    .filter((key) => params[key] !== undefined && params[key] !== null && params[key] !== '')
    .sort();

  const serialized = keys.map((key) => `${key}=${params[key]}`).join('&');
  const stringToSign = `${serialized}${apiSecret}`;

  return crypto.createHash('sha1').update(stringToSign).digest('hex');
};

/**
 * Generates signed parameters for an authenticated user image upload.
 * Folder and public_id are strictly generated by the server.
 *
 * @param userId Authenticated internal user ID (PostgreSQL UUID)
 */
export const generateUploadSignature = (userId: string): UploadSignatureResult => {
  if (!userId) {
    throw new Error('User ID is required to generate an upload signature');
  }

  const cloudName = env.CLOUDINARY_CLOUD_NAME;
  const apiKey = env.CLOUDINARY_API_KEY;
  const apiSecret = env.CLOUDINARY_API_SECRET;

  if (!cloudName || !apiKey || !apiSecret) {
    throw new Error('Cloudinary signing configuration is incomplete');
  }

  // Derive folder using internal database UUID — never user-supplied, never Firebase UID, no PII
  const folder = `creator-connect/profiles/${userId}`;

  // Generate cryptographically secure random public ID
  const publicId = crypto.randomUUID();

  // Timestamp in seconds (Unix epoch)
  const timestamp = Math.floor(Date.now() / 1000);

  // Sign minimum required parameters: folder, public_id, timestamp
  const signature = signParameters(
    {
      folder,
      public_id: publicId,
      timestamp,
    },
    apiSecret
  );

  return {
    signature,
    timestamp,
    apiKey,
    cloudName,
    folder,
    publicId,
    public_id: publicId,
  };
};
